"""Small cooperative credit-assignment benchmarks.

These tasks are not intended to replace SMAC/SMACv2.  They are fast local
diagnostics that isolate sparse delayed team rewards and agent-time credit.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Sequence

import numpy as np


@dataclass(frozen=True)
class DelayedLeverEnv:
    """Delayed global reward with sparse relevant agent-time decisions."""

    horizon: int = 5
    n_agents: int = 4
    n_actions: int = 2
    important: Sequence[tuple[int, int, int]] = (
        (0, 0, 1),
        (1, 1, 1),
        (2, 2, 0),
        (3, 3, 1),
    )
    all_correct_bonus: float = 1.0

    name: str = "delayed_lever"

    def reward(self, actions: np.ndarray) -> float:
        actions = np.asarray(actions, dtype=np.int64)
        if actions.shape != (self.horizon, self.n_agents):
            raise ValueError("actions have wrong shape")
        correct = sum(int(actions[t, i] == target) for t, i, target in self.important)
        dense_part = correct / len(self.important)
        bonus = self.all_correct_bonus if correct == len(self.important) else 0.0
        return float(dense_part + bonus)


@dataclass(frozen=True)
class PairGateEnv:
    """Delayed reward generated by temporally separated pairwise gates."""

    horizon: int = 6
    n_agents: int = 4
    n_actions: int = 2
    gates: Sequence[tuple[tuple[int, int, int], tuple[int, int, int]]] = (
        ((0, 0, 1), (2, 1, 0)),
        ((1, 2, 1), (3, 3, 1)),
        ((4, 0, 0), (5, 2, 1)),
    )
    all_correct_bonus: float = 1.0

    name: str = "pair_gate"

    def reward(self, actions: np.ndarray) -> float:
        actions = np.asarray(actions, dtype=np.int64)
        if actions.shape != (self.horizon, self.n_agents):
            raise ValueError("actions have wrong shape")
        satisfied = 0
        for left, right in self.gates:
            gate_ok = True
            for t, i, target in (left, right):
                gate_ok = gate_ok and actions[t, i] == target
            satisfied += int(gate_ok)
        dense_part = satisfied / len(self.gates)
        bonus = self.all_correct_bonus if satisfied == len(self.gates) else 0.0
        return float(dense_part + bonus)


def make_envs() -> Iterable[DelayedLeverEnv | PairGateEnv]:
    return (DelayedLeverEnv(), PairGateEnv())
